name: Docker CI

on:
  push:
    branches:
      - "main"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "marshallhd/aes-bot-builder"

  build-amd64:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build and push for linux/amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          tags: |
            marshallhd/aes-bot:latest
            marshallhd/aes-bot:${{ github.sha }}
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}

  build-arm64:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build and push for linux/arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          tags: |
            marshallhd/aes-bot:latest
            marshallhd/aes-bot:${{ github.sha }}
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
