name: Docker CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "marshallhd/aes-bot-builder"

      - name: Build and cache for linux/amd64
        id: build-amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          tags: |
            marshallhd/aes-bot:cache-amd64
          outputs: type=cache

      - name: Build and cache for linux/arm64
        id: build-arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          tags: |
            marshallhd/aes-bot:cache-arm64
          outputs: type=cache

      - name: Combine and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            marshallhd/aes-bot:latest
            marshallhd/aes-bot:${{ github.sha }}
          build-args: |
            CACHE_AMD64=${{ steps.build-amd64.outputs.cache }}
            CACHE_ARM64=${{ steps.build-arm64.outputs.cache }}
          outputs: type=registry,push=true
